import {test} from 'node:test';
import assert from 'node:assert/strict';
import {api} from '../server/api.mjs';
import {fixtureDatabase as localDatabase, fixtureHeaders} from './session-fixture.mjs';
const origin='https://ssr.example';
const user=fixtureHeaders;
const initial={name:'OPC Cement',brand:'Test brand',category:'Cement',project:'Nakshatra',unit:'Bags',supplier:'Test supplier',specification:'53 grade',quantity:10,minimum:2,price:400,receivedOn:'2026-01-01T00:00:00Z',reference:'TEST-001'};
function call(DB,path,method='GET',body,key=crypto.randomUUID(),headers=user){return api(new Request(origin+path,{method,headers:{...headers,origin,'content-type':'application/json','idempotency-key':key},...(body?{body:JSON.stringify(body)}:{})}),{DB});}
async function setup(){const DB=await localDatabase();const response=await call(DB,'/api/materials','POST',initial);assert.equal(response.status,201);return{DB,id:(await response.json()).id};}
test('identity and origin are required for protected data and writes',async()=>{const DB=await localDatabase();assert.equal((await call(DB,'/api/state','GET',null,undefined,{})).status,401);const request=new Request(origin+'/api/materials',{method:'POST',headers:{...user,origin:'https://evil.test','content-type':'application/json'},body:JSON.stringify(initial)});assert.equal((await api(request,{DB})).status,403);DB.close();});
test('material creation is durable, attributed and idempotent',async()=>{const DB=await localDatabase(),key=crypto.randomUUID();const a=await call(DB,'/api/materials','POST',initial,key),b=await call(DB,'/api/materials','POST',initial,key);assert.equal((await a.json()).id,(await b.json()).id);const state=await(await call(DB,'/api/state')).json();assert.equal(state.materials.length,1);assert.equal(state.movements.length,1);assert.equal(state.materials[0].createdBy,'owner@example.test');assert.equal(state.movements[0].balance,10);assert.equal((await call(DB,'/api/materials','POST',{...initial,quantity:50},key)).status,409);DB.close();});
test('concurrent stock issues cannot overspend or lose history',async()=>{const{DB,id}=await setup();const payload={version:1,type:'issued',quantity:7,note:'Site use',occurredAt:'2026-01-02T00:00:00Z',party:'Site team',batch:'A1'};const responses=await Promise.all([call(DB,`/api/materials/${id}/movements`,'POST',payload),call(DB,`/api/materials/${id}/movements`,'POST',payload)]);assert.deepEqual(responses.map(r=>r.status).sort(),[200,409]);const state=await(await call(DB,'/api/state')).json();assert.equal(state.materials[0].quantity,3);assert.equal(state.movements.length,2);assert.equal(state.movements.find(m=>m.type==='issued').batch,'A1');assert.equal((await call(DB,`/api/materials/${id}/movements`,'POST',{...payload,quantity:4,version:2})).status,422);DB.close();});
test('editing preserves original stock identity and uses optimistic versions',async()=>{const{DB,id}=await setup();const payload={...initial,version:1,name:'Updated cement',brand:'Attempted different brand',quantity:100,supplier:'Updated supplier'};assert.equal((await call(DB,`/api/materials/${id}`,'PATCH',payload)).status,200);assert.equal((await call(DB,`/api/materials/${id}`,'PATCH',payload)).status,409);const state=await(await call(DB,'/api/state')).json();assert.equal(state.materials[0].quantity,10);assert.equal(state.materials[0].brand,'Test brand');assert.equal(state.materials[0].changes.length,1);DB.close();});
test('server validates negative, excessive precision and invalid dates',async()=>{const DB=await localDatabase();for(const changes of [{quantity:-1},{quantity:0.001},{category:'Unknown'},{receivedOn:'not-a-date'},{name:' '},{price:Infinity}])assert.equal((await call(DB,'/api/materials','POST',{...initial,...changes})).status,422);assert.equal((await(await call(DB,'/api/state')).json()).materials.length,0);DB.close();});
