'use strict';
const $ = s => document.querySelector(s);
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number = n => n.toLocaleString('en-IN', {maximumFractionDigits:2});
const money = n => '₹' + number(Math.round(n));
const compact = n => n >= 100000 ? '₹' + (n / 100000).toFixed(2) + ' L' : money(n);
const projects = ['Nakshatra','HM Grandeur','Sri Sai Bhageeratha Residency'];
let materials = [
 {id:1,name:'OPC 53 Grade Cement',category:'Cement',unit:'Bags',quantity:850,minimum:300,price:390,project:'Nakshatra'},
 {id:2,name:'TMT Steel · Fe 550',category:'Steel',unit:'Tonnes',quantity:4.5,minimum:8,price:58000,project:'Nakshatra'},
 {id:3,name:'AAC Blocks · 6 inch',category:'Masonry',unit:'Nos',quantity:2400,minimum:1000,price:68,project:'HM Grandeur'},
 {id:4,name:'River Sand',category:'Aggregates',unit:'Cu ft',quantity:650,minimum:1000,price:55,project:'Nakshatra'},
 {id:5,name:'Copper Wire · 2.5 sq mm',category:'Electrical',unit:'Metres',quantity:1800,minimum:500,price:32,project:'HM Grandeur'},
 {id:6,name:'CPVC Pipe · 25 mm',category:'Plumbing',unit:'Metres',quantity:0,minimum:200,price:110,project:'Sri Sai Bhageeratha Residency'},
 {id:7,name:'Vitrified Tiles · 600 × 600',category:'Finishing',unit:'Sq ft',quantity:3200,minimum:800,price:65,project:'HM Grandeur'},
 {id:8,name:'Interior Wall Putty',category:'Finishing',unit:'Bags',quantity:180,minimum:80,price:780,project:'Sri Sai Bhageeratha Residency'}
];
let movements = [
 {id:1,materialId:1,type:'received',quantity:300,note:'Demo · DC-1024',time:'Sample entry'},
 {id:2,materialId:3,type:'issued',quantity:500,note:'Demo · First-floor masonry',time:'Sample entry'},
 {id:3,materialId:5,type:'received',quantity:800,note:'Demo · DC-1021',time:'Sample entry'}
];
const categories=['Cement','Steel','Aggregates','Masonry','Electrical','Plumbing','Finishing','Waterproofing','Other'];
const storageKey='ssr-materials-v1';
const dateText=value=>value?new Date(value).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' IST':'Not recorded';
const localDate=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
const code=m=>'MAT-'+String(m.id).padStart(3,'0');
materials=materials.map(m=>({...m,brand:'Not recorded',supplier:'',specification:m.name,createdAt:null,updatedAt:null,demo:true,changes:[]}));
movements=movements.map(m=>({...m,recordedAt:null,occurredAt:null,party:'Not recorded',batch:'',demo:true}));
let storageBlocked=false;
function storageWarning(message){$('#storage-warning').hidden=false;$('#storage-warning').textContent=message;}
try {
 const raw=localStorage.getItem(storageKey);
 if(raw){const data=JSON.parse(raw);const valid=data.version===1&&Array.isArray(data.materials)&&Array.isArray(data.movements)&&data.materials.every(m=>Number.isInteger(m.id)&&typeof m.name==='string'&&typeof m.brand==='string'&&categories.includes(m.category)&&projects.includes(m.project)&&[m.quantity,m.minimum,m.price].every(n=>Number.isFinite(n)&&n>=0)&&Array.isArray(m.changes))&&data.movements.every(v=>data.materials.some(m=>m.id===v.materialId)&&['received','issued'].includes(v.type)&&Number.isFinite(v.quantity)&&v.quantity>0);
 if(!valid)throw new Error('Invalid saved data');materials=data.materials;movements=data.movements;}
}catch(error){storageBlocked=true;storageWarning('Saved records could not be loaded. Saving is disabled to protect them; export any changes before closing this page.');}
function persist(){if(storageBlocked)return false;try{localStorage.setItem(storageKey,JSON.stringify({version:1,materials,movements}));return true;}catch(error){storageWarning('Browser storage is unavailable or full. Changes are not saved; export your records before closing this page.');return false;}}
let editingId=null,detailId=null;
let view='inventory', status='all', activeId=null, toastTimer;
const stockStatus = m => m.quantity===0 ? 'out' : m.quantity<=m.minimum ? 'low':'ok';
const statusName = s => ({out:'Out of stock',low:'Low stock',ok:'In stock'}[s]);
const projectMaterials = () => materials.filter(m => $('#project').value==='all'||m.project===$('#project').value);
function matchesMaterial(m){const q=$('#search').value.trim().toLowerCase();return ($('#category').value==='all'||m.category===$('#category').value)&&($('#brand-filter').value==='all'||m.brand===$('#brand-filter').value)&&[m.name,code(m),m.project,m.brand,m.supplier,m.specification].join(' ').toLowerCase().includes(q);}
function filteredMaterials(){return projectMaterials().filter(m=>(status==='all'||stockStatus(m)===status)&&matchesMaterial(m)).sort((a,b)=>categories.indexOf(a.category)-categories.indexOf(b.category)||a.name.localeCompare(b.name));}
function filteredMovements(){const ids=new Set(projectMaterials().filter(m=>($('#category').value==='all'||m.category===$('#category').value)&&($('#brand-filter').value==='all'||m.brand===$('#brand-filter').value)).map(m=>m.id));const q=$('#search').value.trim().toLowerCase();return movements.filter(v=>{const m=materials.find(m=>m.id===v.materialId);return ids.has(v.materialId)&&[m.name,code(m),m.brand,m.category,m.project,v.note,v.party,v.batch].join(' ').toLowerCase().includes(q);});}
function movementDate(v){return v.occurredAt?dateText(v.occurredAt):'Sample entry · date not recorded';}
function render(){
 const selectedBrand=$('#brand-filter').value;$('#brand-filter').innerHTML='<option value="all">All brands</option>'+[...new Set(materials.map(m=>m.brand))].sort().map(b=>`<option value="${esc(b)}">${esc(b)}</option>`).join('');$('#brand-filter').value=selectedBrand;
 const list=projectMaterials(), low=list.filter(m=>stockStatus(m)==='low'),out=list.filter(m=>stockStatus(m)==='out');
 $('#category-overview').innerHTML=['all',...categories].map(c=>{const subset=list.filter(m=>c==='all'||m.category===c);return `<button class="category-card ${$('#category').value===c?'selected':''}" data-category="${esc(c)}" aria-pressed="${$('#category').value===c}"><span>${c==='all'?'All categories':esc(c)}</span><strong>${subset.length}</strong><small>${compact(subset.reduce((n,m)=>n+m.price*m.quantity,0))}</small></button>`;}).join('');
 const total=list.reduce((n,m)=>n+m.price*m.quantity,0);
 const cards=[['Stock value',compact(total),'At current material unit costs','₹'],['Materials tracked',number(list.length),'Across '+new Set(list.map(m=>m.project)).size+' project sites','▦'],['Low-stock materials',number(low.length),'At or below reorder level','↘'],['Out of stock',number(out.length),out.length?'Restocking required':'All materials available','□']];
 $('#metrics').innerHTML=cards.map(([label,value,note,icon])=>`<article class="metric"><div class="metric-head">${label}<span class="metric-icon">${icon}</span></div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></article>`).join('');
 $('#page-title').textContent=view==='inventory'?'Material Management':'Stock Movements';$('#crumb').textContent=$('#page-title').textContent;
 $('.tabs').hidden=view!=='inventory';$('#table-title').innerHTML=(view==='inventory'?'Material inventory':'Movement register')+' <span id="count" class="count"></span>';
 $('#table-description').textContent=view==='inventory'?'A clear view of stock across your construction sites.':'Receipts and issues, with a reference for every update.';
 $('#low-count').textContent=low.length;
 document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));
 if(view==='inventory'){
 const items=filteredMaterials();$('#count').textContent=items.length;
 $('#table-head').innerHTML='<tr><th>Material / brand</th><th>Date added</th><th>Available</th><th>Stock value</th><th>Status</th><th>Actions</th></tr>';
 let lastCategory='';
 $('#rows').innerHTML=items.map(m=>{let group='';if(m.category!==lastCategory){lastCategory=m.category;group=`<tr class="category-row"><th colspan="6" scope="rowgroup">${esc(m.category)} <span class="count">${items.filter(x=>x.category===m.category).length}</span></th></tr>`;}return group+`<tr><td><button class="material-link" data-detail="${m.id}">${esc(m.name)}</button><small>${esc(m.brand)} · ${code(m)}${m.demo?' · SAMPLE':''}</small><small>${esc(m.project)}</small></td><td class="date-cell">${m.createdAt?esc(dateText(m.createdAt)):'Not recorded'}${m.demo?'<small>Sample material</small>':''}</td><td><span class="quantity">${number(m.quantity)}</span> <span class="unit">${esc(m.unit)}</span><small>Min. ${number(m.minimum)}</small></td><td>${money(m.price*m.quantity)}</td><td><span class="badge ${stockStatus(m)}">${statusName(stockStatus(m))}</span></td><td><div class="row-actions"><button class="row-action" data-detail="${m.id}" aria-label="View details for ${esc(m.name)}">Details</button><button class="row-action" data-stock="${m.id}" aria-label="Update stock for ${esc(m.name)}">Update</button></div></td></tr>`;}).join('')||'<tr><td colspan="6" class="empty">No materials match your filters. Try another search or add a material.</td></tr>';
 $('#results').textContent=`Showing ${items.length} of ${list.length} materials`;
 }else{
 const items=filteredMovements();$('#count').textContent=items.length;
 $('#table-head').innerHTML='<tr><th>Material / brand</th><th>Movement</th><th>Quantity</th><th>Reference / party</th><th>Movement date</th></tr>';
 $('#rows').innerHTML=items.map(v=>{const m=materials.find(m=>m.id===v.materialId);return `<tr><td><strong>${esc(m.name)}</strong><small>${esc(m.brand)} · ${esc(m.category)}</small><small>${esc(m.project)}</small></td><td><span class="badge ${v.type==='received'?'ok':'low'}">${v.type==='received'?'Received':'Issued'}</span></td><td>${number(v.quantity)} ${esc(m.unit)}</td><td>${esc(v.note)}<small>${esc(v.party||"Not recorded")}${v.batch?" · Batch "+esc(v.batch):""}</small></td><td class="date-cell">${esc(movementDate(v))}<small>Logged: ${v.recordedAt?esc(dateText(v.recordedAt)):"Not recorded"}</small></td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">No movements match your filters.</td></tr>';
 $('#results').textContent=`Showing ${items.length} movements`;
 }
 const alerts=[...out,...low];$('#alert-count').textContent=alerts.length;
 $('#alerts').innerHTML=alerts.map(m=>`<div class="alert-item"><strong>${esc(m.name)}</strong><small>${esc(m.project)}</small><div class="alert-line"><span>${number(m.quantity)} ${esc(m.unit)} remaining</span><button data-stock="${m.id}">Update stock</button></div></div>`).join('')||'<p class="empty">All materials are above their reorder levels.</p>';
 const ids=new Set(list.map(m=>m.id));$('#activity').innerHTML=movements.filter(v=>ids.has(v.materialId)).slice(0,3).map(v=>{const m=materials.find(m=>m.id===v.materialId);return `<div class="activity-item"><span class="movement-icon ${v.type}">${v.type==='received'?'↓':'↑'}</span><div><strong>${esc(m.name)}</strong><p>${v.type==='received'?'+':'−'}${number(v.quantity)} ${esc(m.unit)} · ${esc(m.project)}</p><small>${esc(movementDate(v))}</small></div></div>`;}).join('')||'<p class="empty">No stock movements yet.</p>';
 $('#project-bars').innerHTML=projects.filter(p=>$('#project').value==='all'||$('#project').value===p).map(p=>{const value=list.filter(m=>m.project===p).reduce((n,m)=>n+m.price*m.quantity,0);return `<div class="project-bar"><span>${esc(p)}</span><div class="bar-track" role="img" aria-label="${esc(p)}: ${money(value)}"><div class="bar-fill" style="width:${total?100*value/total:0}%"></div></div><b>${compact(value)}</b></div>`;}).join('');
}
function showToast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').style.display='block';toastTimer=setTimeout(()=>$('#toast').style.display='none',4000);}
function setView(next){view=next;$('#search').value='';status='all';document.querySelectorAll('[data-status]').forEach(b=>{b.classList.toggle('selected',b.dataset.status==='all');b.setAttribute('aria-selected',String(b.dataset.status==='all'));});render();}
function openStock(id){activeId=id;const m=materials.find(m=>m.id===id);$('#stock-form').reset();$('#stock-form').elements.occurredAt.value=localDate();$('#stock-form').elements.party.value=m.supplier;$('#stock-error').textContent='';$('#stock-material').textContent=`${m.name} · ${m.brand} · ${m.project} · Available: ${number(m.quantity)} ${m.unit}`;$('#stock-dialog').showModal();}
function openMaterial(id=null){editingId=id;const form=$('#material-form');form.reset();$('#material-error').textContent='';$('#material-form-title').textContent=id?'Edit material details':'Add a material';$('#material-submit').textContent=id?'Save details':'Add material';form.elements.quantity.disabled=Boolean(id);form.elements.receivedOn.disabled=Boolean(id);$('#opening-fields').hidden=Boolean(id);form.elements.receivedOn.value=localDate();if(id){const m=materials.find(m=>m.id===id);for(const field of ['name','brand','supplier','specification','category','unit','project','quantity','minimum','price'])form.elements[field].value=m[field];}else{if($('#project').value!=='all')form.elements.project.value=$('#project').value;if($('#category').value!=='all')form.elements.category.value=$('#category').value;}
 // Units, brand and project identify a stock ledger; create a separate record to change these after creation.
 for(const field of ['unit','project'])form.elements[field].disabled=Boolean(id);form.elements.brand.disabled=Boolean(id&&materials.find(m=>m.id===id).brand!=='Not recorded');
 $('#material-dialog').showModal();}
function openDetails(id){detailId=id;const m=materials.find(m=>m.id===id);$('#detail-title').textContent=m.name;$('#detail-code').textContent=code(m)+' · '+m.category+(m.demo?' · SAMPLE MATERIAL':'');const facts=[['Category',m.category],['Brand / manufacturer',m.brand],['Supplier',m.supplier||'Not recorded'],['Specifications / grade',m.specification||'Not recorded'],['Project',m.project],['Available stock',number(m.quantity)+' '+m.unit],['Reorder level',number(m.minimum)+' '+m.unit],['Unit cost',money(m.price)],['Date added',dateText(m.createdAt)],['Last updated',dateText(m.updatedAt)]];
 const events=[...movements.filter(v=>v.materialId===id).map(v=>({sort:v.recordedAt||'',html:`<article class="history-item"><div><strong>${v.type==='received'?'Received':'Issued'} ${number(v.quantity)} ${esc(m.unit)}</strong><span>${esc(movementDate(v))}</span></div><p>${esc(v.note)} · ${esc(v.party||'Party not recorded')}${v.batch?' · Batch '+esc(v.batch):''}</p><small>Recorded: ${dateText(v.recordedAt)}${v.balance!==undefined?' · Balance after: '+number(v.balance)+' '+esc(m.unit):''}</small></article>`})),...m.changes.map(c=>({sort:c.recordedAt,html:`<article class="history-item"><div><strong>Material details updated</strong><span>${dateText(c.recordedAt)}</span></div><p>${esc(c.note)}</p></article>`}))].sort((a,b)=>b.sort.localeCompare(a.sort));
 $('#detail-body').innerHTML=`<dl class="material-facts">${facts.map(([label,value])=>`<div><dt>${label}</dt><dd>${esc(value)}</dd></div>`).join('')}</dl><h3>Material history</h3><p class="history-note">Movement dates show when material was received or issued. Recorded dates show when the entry was made. All times are IST.</p>${events.map(e=>e.html).join('')||'<p class="empty">No stock movements recorded for this material.</p>'}`;$('#detail-dialog').showModal();}
function chooseCategory(value){$('#category').value=value;render();}
document.addEventListener('click',e=>{const stock=e.target.closest('[data-stock]');if(stock)openStock(Number(stock.dataset.stock));const detail=e.target.closest('[data-detail]');if(detail)openDetails(Number(detail.dataset.detail));const category=e.target.closest('[data-category]');if(category)chooseCategory(category.dataset.category);const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const tab=e.target.closest('[data-status]');if(tab){status=tab.dataset.status;document.querySelectorAll('[data-status]').forEach(b=>{b.classList.toggle('selected',b===tab);b.setAttribute('aria-selected',String(b===tab));});render();}if(e.target.closest('.close-dialog'))e.target.closest('dialog').close();});
for(const id of ['project','category','brand-filter'])$('#'+id).addEventListener('change',render);$('#search').addEventListener('input',render);
$('#add').onclick=()=>openMaterial();$('#view-movements').onclick=()=>setView('movements');
$('#edit-material').onclick=()=>{$('#detail-dialog').close();openMaterial(detailId);};$('#detail-stock').onclick=()=>{$('#detail-dialog').close();openStock(detailId);};
$('#material-form').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,data=Object.fromEntries(new FormData(form)),now=new Date().toISOString();data.name=data.name.trim();data.brand=(data.brand||'').trim();if(!data.name||(!form.elements.brand.disabled&&!data.brand)){$('#material-error').textContent='Enter a material name and brand (or Unbranded).';return;}let m;
 if(editingId){m=materials.find(m=>m.id===editingId);const changes=[];for(const key of ['name','supplier','specification','category','minimum','price',...(m.brand==='Not recorded'?['brand']:[])]){const value=['minimum','price'].includes(key)?Number(data[key]):data[key].trim();if(m[key]!==value)changes.push(`${key}: ${m[key]||'Not recorded'} → ${value||'Not recorded'}`);m[key]=value;}if(changes.length){m.updatedAt=now;m.changes.unshift({recordedAt:now,note:changes.join('; ')});}}
 else{const receivedOn=new Date(data.receivedOn);if(!Number.isFinite(receivedOn.getTime())||receivedOn>new Date()){$('#material-error').textContent='Enter a valid received date that is not in the future.';return;}m={id:Math.max(...materials.map(m=>m.id),0)+1,name:data.name,brand:data.brand,supplier:data.supplier.trim(),specification:data.specification.trim(),category:data.category,unit:data.unit,project:data.project,quantity:Number(data.quantity),minimum:Number(data.minimum),price:Number(data.price),createdAt:now,updatedAt:now,demo:false,changes:[]};materials.push(m);if(m.quantity)movements.unshift({id:crypto.randomUUID(),materialId:m.id,type:'received',quantity:m.quantity,note:data.reference.trim()||'Opening stock',recordedAt:now,occurredAt:receivedOn.toISOString(),party:m.supplier,batch:'',balance:m.quantity});}
 const saved=persist();$('#material-dialog').close();$('#project').value=m.project;$('#category').value='all';$('#brand-filter').value='all';setView('inventory');showToast((editingId?'Material details updated':'Material added')+(saved?' · Saved in this browser':' · Not saved to browser'));};
$('#stock-form').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget)),quantity=Number(data.quantity),m=materials.find(m=>m.id===activeId),occurredAt=new Date(data.occurredAt);if(!data.note.trim()){$('#stock-error').textContent='Enter a reference or note.';return;}if(!Number.isFinite(occurredAt.getTime())||occurredAt>new Date()){$('#stock-error').textContent='Enter a valid movement date that is not in the future.';return;}if(data.type==='issued'&&quantity>m.quantity){$('#stock-error').textContent=`Only ${number(m.quantity)} ${m.unit} available. Enter a smaller quantity.`;return;}const now=new Date().toISOString();m.quantity=Math.round((m.quantity+(data.type==='received'?quantity:-quantity))*100)/100;m.updatedAt=now;movements.unshift({id:crypto.randomUUID(),materialId:m.id,type:data.type,quantity,note:data.note.trim(),recordedAt:now,occurredAt:occurredAt.toISOString(),party:data.party.trim(),batch:data.batch.trim(),balance:m.quantity});const saved=persist();$('#stock-dialog').close();render();showToast('Stock updated'+(saved?' · Saved in this browser':' · Not saved to browser'));};
$('#export').onclick=()=>{const data=view==='inventory'?[['Code','Material','Category','Brand','Supplier','Specifications','Project','Available','Unit','Reorder level','Unit cost INR','Stock value INR','Status','Date added (ISO)','Last updated (ISO)','Sample record'],...filteredMaterials().map(m=>[code(m),m.name,m.category,m.brand,m.supplier,m.specification,m.project,m.quantity,m.unit,m.minimum,m.price,m.quantity*m.price,statusName(stockStatus(m)),m.createdAt||'',m.updatedAt||'',m.demo?'Yes':'No'])]:[['Code','Material','Category','Brand','Project','Type','Quantity','Unit','Reference','Supplier or recipient','Batch','Movement date (ISO)','Recorded date (ISO)','Balance after'],...filteredMovements().map(v=>{const m=materials.find(m=>m.id===v.materialId);return[code(m),m.name,m.category,m.brand,m.project,v.type,v.quantity,m.unit,v.note,v.party,v.batch,v.occurredAt||'',v.recordedAt||'',v.balance??''];})];const csv=data.map(row=>row.map(value=>{let s=String(value??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=`SSR-${view}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Filtered '+view+' exported');};
render();
