import { authorize, AuthError } from './auth.mjs';
export const categories=['Cement','Steel','Aggregates','Masonry','Electrical','Plumbing','Finishing','Waterproofing','Other'];
export const projects=['Nakshatra','HM Grandeur','Sri Sai Bhageeratha Residency'];
const units=['Bags','Tonnes','Nos','Metres','Sq ft','Cu ft','Litres'];
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'private, no-store','x-content-type-options':'nosniff'}});
class Problem extends Error{constructor(status,message){super(message);this.status=status;}}
const problem=(status,message)=>{throw new Problem(status,message);};
const text=(v,label,max=180,required=false)=>{if(v===undefined||v===null)v='';if(typeof v!=='string'||v.length>max)problem(422,`${label} must be text of at most ${max} characters.`);v=v.trim();if(required&&!v)problem(422,`${label} is required.`);return v;};
const choice=(v,list,label)=>list.includes(v)?v:problem(422,`Choose a valid ${label}.`);
const amount=(v,label,min=0)=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>100000000||Math.abs(v*100-Math.round(v*100))>0.00001)problem(422,`${label} must be between ${min} and 100000000, with at most two decimal places.`);return Math.round(v*100);};
const stamp=(v,label)=>{if(typeof v!=='string'||!Number.isFinite(Date.parse(v))||Date.parse(v)>Date.now()+60000)problem(422,`${label} must be a valid date that is not in the future.`);return new Date(v).toISOString();};
const uuid=v=>typeof v==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(v);
function dbFor(env){if(!env.DB?.prepare)problem(503,'The shared database is temporarily unavailable. Please try again.');return env.DB;}
const material=r=>({id:r.id,name:r.name,category:r.category,brand:r.brand,supplier:r.supplier,specification:r.specification,project:r.project,unit:r.unit,quantity:r.quantity100/100,minimum:r.minimum100/100,price:r.price100/100,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at,createdBy:r.created_by,updatedBy:r.updated_by,demo:false,changes:[]});
const movement=r=>({id:r.id,materialId:r.material_id,type:r.type,quantity:r.quantity100/100,balance:r.balance100/100,note:r.note,party:r.party,batch:r.batch,occurredAt:r.occurred_at,recordedAt:r.recorded_at,actorName:r.actor_name});
async function state(db,user){const [m,v,a]=await db.batch([db.prepare('SELECT * FROM materials ORDER BY created_at DESC'),db.prepare('SELECT * FROM movements ORDER BY recorded_at DESC, id DESC'),db.prepare("SELECT * FROM audit WHERE action = 'updated' ORDER BY recorded_at DESC")]);const records=m.results.map(material);for(const row of a.results){const entry=records.find(m=>m.id===row.material_id);if(entry)entry.changes.push({note:row.note,recordedAt:row.recorded_at,actorName:row.actor_name});}return{materials:records,movements:v.results.map(movement),user,serverTime:new Date().toISOString()};}
async function fingerprint(method,path,body){const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify([method,path,body])));return Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');}
async function prior(db,key,user,hash){const row=await db.prepare('SELECT * FROM requests WHERE id = ?').bind(key).first();if(!row)return null;if(row.actor_id!==user.id||row.fingerprint!==hash)problem(409,'This request key was already used for a different operation. Refresh and try again.');return JSON.parse(row.response_json);}
function auditStatement(db,{id,action,note,before,after,now,user},conditional=false){return db.prepare(`INSERT INTO audit (id,material_id,action,note,before_json,after_json,recorded_at,actor_id,actor_name) SELECT ?,?,?,?,?,?,?,?,?${conditional?' WHERE changes() = 1':''}`).bind(crypto.randomUUID(),id,action,note,before?JSON.stringify(before):null,after?JSON.stringify(after):null,now,user.id,user.name);}
function requestStatement(db,key,user,hash,result,now,conditional=false){return db.prepare(`INSERT INTO requests (id,actor_id,fingerprint,response_json,created_at) SELECT ?,?,?,?,?${conditional?' WHERE changes() = 1':''}`).bind(key,user.id,hash,JSON.stringify(result),now);}
async function runMutation(db,statements,key,user,hash){try{return await db.batch(statements);}catch(error){const saved=await prior(db,key,user,hash);if(saved)return{replayed:saved};throw error;}}
export async function api(request,env){try{
 const account=await authorize(request,env);const user={id:account.id,name:account.name,username:account.username,role:account.role};
 const url=new URL(request.url),path=url.pathname,db=dbFor(env);
 if(request.method==='GET'&&path==='/api/state')return json(await state(db,user));
 if(!['POST','PATCH'].includes(request.method))return json({error:'Endpoint not found.'},404);
 if(request.headers.get('origin')!==url.origin||request.headers.get('sec-fetch-site')==='cross-site')problem(403,'The request must come from this dashboard.');
 if(!(request.headers.get('content-type')||'').startsWith('application/json'))problem(415,'Use JSON for this request.');
 if(Number(request.headers.get('content-length'))>20000)problem(413,'The request is too large.');
 const raw=await request.text();if(raw.length>20000)problem(413,'The request is too large.');let body;try{body=JSON.parse(raw);}catch{problem(400,'Invalid request data.');}if(!body||Array.isArray(body)||typeof body!=='object')problem(400,'Invalid request data.');
 const key=request.headers.get('idempotency-key');if(!uuid(key))problem(400,'A valid request key is required.');const hash=await fingerprint(request.method,path,body),saved=await prior(db,key,user,hash);if(saved)return json(saved);
 const now=new Date().toISOString();
 if(path==='/api/materials'&&request.method==='POST'){
  const id=crypto.randomUUID(),name=text(body.name,'Material name',80,true),brand=text(body.brand,'Brand',80,true),supplier=text(body.supplier,'Supplier',100),specification=text(body.specification,'Specifications',180),category=choice(body.category,categories,'category'),project=choice(body.project,projects,'project'),unit=choice(body.unit,units,'unit'),quantity100=amount(body.quantity,'Opening stock'),minimum100=amount(body.minimum,'Reorder level',0.01),price100=amount(body.price,'Unit cost'),receivedOn=stamp(body.receivedOn,'Received date'),reference=text(body.reference,'Delivery reference',120)||'Opening stock';
  const result={id,message:'Material created.'};const statements=[db.prepare('INSERT INTO materials (id,name,category,brand,supplier,specification,project,unit,quantity100,minimum100,price100,version,created_at,updated_at,created_by,updated_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,1,?,?,?,?)').bind(id,name,category,brand,supplier,specification,project,unit,quantity100,minimum100,price100,now,now,user.name,user.name)];
  if(quantity100)statements.push(db.prepare("INSERT INTO movements (id,material_id,type,quantity100,balance100,note,party,batch,occurred_at,recorded_at,actor_id,actor_name) VALUES (?,?,'received',?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),id,quantity100,quantity100,reference,supplier,'',receivedOn,now,user.id,user.name));
  statements.push(auditStatement(db,{id,action:'created',note:'Material created',before:null,after:{name,category,brand,supplier,specification,project,unit,quantity100,minimum100,price100},now,user}),requestStatement(db,key,user,hash,result,now));const applied=await runMutation(db,statements,key,user,hash);return json(applied.replayed||result,201);
 }
 const match=path.match(/^\/api\/materials\/([a-f0-9-]+)(\/movements)?$/i);if(!match||!uuid(match[1]))problem(404,'Material not found.');const id=match[1],row=await db.prepare('SELECT * FROM materials WHERE id=?').bind(id).first();if(!row)problem(404,'Material not found.');if(!Number.isInteger(body.version)||body.version!==row.version)problem(409,'This material was changed by another session. Close this form, refresh the inventory, and reopen the material before submitting again.');const before=material(row),result={id,message:'Saved.'};let statements;
 if(!match[2]&&request.method==='PATCH'){
  const next={name:text(body.name,'Material name',80,true),category:choice(body.category,categories,'category'),supplier:text(body.supplier,'Supplier',100),specification:text(body.specification,'Specifications',180),minimum100:amount(body.minimum,'Reorder level',0.01),price100:amount(body.price,'Unit cost')};
  const note=Object.entries(next).filter(([k,v])=>row[k]!==v).map(([k,v])=>`${k.replace('100','')}: ${String(k.endsWith('100')?row[k]/100:row[k])} → ${String(k.endsWith('100')?v/100:v)}`).join('; ')||'Details reviewed';
  statements=[db.prepare('UPDATE materials SET name=?,category=?,supplier=?,specification=?,minimum100=?,price100=?,version=version+1,updated_at=?,updated_by=? WHERE id=? AND version=?').bind(next.name,next.category,next.supplier,next.specification,next.minimum100,next.price100,now,user.name,id,row.version),auditStatement(db,{id,action:'updated',note,before,after:next,now,user},true),requestStatement(db,key,user,hash,result,now,true)];
 }else if(match[2]&&request.method==='POST'){
  const type=choice(body.type,['received','issued'],'movement type'),quantity100=amount(body.quantity,'Quantity',0.01),note=text(body.note,'Reference',120,true),party=text(body.party,'Supplier or recipient',100),batch=text(body.batch,'Batch',80),occurredAt=stamp(body.occurredAt,'Movement date'),delta=type==='received'?quantity100:-quantity100;
  if(row.quantity100+delta<0)problem(422,`Only ${row.quantity100/100} ${row.unit} available.`);if(row.quantity100+delta>10000000000)problem(422,'The resulting stock exceeds the supported quantity.');
  statements=[db.prepare('UPDATE materials SET quantity100=quantity100+?,version=version+1,updated_at=?,updated_by=? WHERE id=? AND version=? AND quantity100+? >= 0').bind(delta,now,user.name,id,row.version,delta),db.prepare('INSERT INTO movements (id,material_id,type,quantity100,balance100,note,party,batch,occurred_at,recorded_at,actor_id,actor_name) SELECT ?,id,?,?,quantity100,?,?,?,?,?,?,? FROM materials WHERE id=? AND changes()=1').bind(crypto.randomUUID(),type,quantity100,note,party,batch,occurredAt,now,user.id,user.name,id),auditStatement(db,{id,action:type,note,before:{quantity:before.quantity},after:{quantity:(row.quantity100+delta)/100},now,user},true),requestStatement(db,key,user,hash,result,now,true)];
 }else problem(405,'Method not allowed.');
 const applied=await runMutation(db,statements,key,user,hash);if(applied.replayed)return json(applied.replayed);if(applied[0].meta.changes!==1)problem(409,'Stock changed while you were saving. Refresh and try again.');return json(result);
 }catch(error){if(error instanceof Problem||error instanceof AuthError)return json({error:error.message,...error.extra},error.status);console.error('SSR API failure',error?.name);return json({error:'The server could not complete this request. Your entries are still in the form; please try again.'},503);}}
